### ISSUE TITLE
Users should have leaderboard points fields

### ISSUE THREAD

**Issue by Henry-Graves** [ucf-tower-app/xplat#104]
### Tasks for this requirement:
- [ ] Global Leaderboard score
- [ ] Monthly Leaderboard score (Monthly leaderboard scores are reset for each user at the start of each month)
- [ ] Fetch the current user's score & leaderboard position. 

Here's the Figma, note that we aren't just counting sends anymore since we have a difficulty-to-points system now.
![image](https://user-images.githubusercontent.com/73561858/215091899-42aae7eb-d742-47bf-831c-4fbb50bcfda3.png)

**My thoughts on the process:**
- make a leaderboard collection in db (user, total points, this month's points)

- on route send/unsend, update user points

- make a querycursor over the collection in desc order to return list

- make a query to get current user's points (this is in the Figma)
   - it may be difficult to get this user's current position bc that info is coming from querycursor sorting
       - just show score this user's score? 
       - read the whole list once on first load of that view then cache it locally, not updating their position on every new send?

- if we're storing leaderboard positions, update everyone's position once a day? Is it worth the expense to keep leaderboards updated after every/every few routes sent? Will users get that much value out of it?

- monthly leaderboard reset implementation:
    - use cloud functions to set up a scheduled function that runs once a month, using the schedule package to run a function at a specific time of the day

**Comment by JakeSteinebronn** [comment]
First of all, I don't think we should maintain a global leaderboard. I feel like this would just result in someone running away with it and then being there for all time. Maybe a semesterly leaderboard would be good? [Aug-Dec], [Jan-May], [Jun-Jul]

Then we can have a leaderboard collection with a bunch of documents, one per month, and each of these documents contains a map of user -> points. We can sort on client-side to get positions and such. And yeah, we update this upon every send, but that's fine because transactions are based

We don't really want to show the user's score, because it's kinda weird. Maybe total sends, and then it'll have to be explained that someone can beat you with fewer sends if they're harder, and just leave it kinda mysterious

**Comment by JakeSteinebronn** [comment]
The new arch is already implemented, this is kind of an artifact
