### ISSUE TITLE
Employees can process reported content

### ISSUE THREAD

**Issue by Henry-Graves** [ucf-tower-app/xplat#105]
### Tasks for this requirement:

**Users can report posts & comments:** 
Note for front-end: instead of having report reasons, just show users an "are you sure?" popup, users can un-report things
- [x] posts & comments send reports to a db collection instead of being stored on the object
- [x] users can report and undo the report
    - [x] automatically hide content after 3 reports (employees can then get rid of the reports to unhide)
    - [x] users are not allowed to report an employee/manager's content

**Employees can review reported content:**
- [x] Employee actions:
    - [x] mark the content as okay (remove all reports on it)
    - [x] delete the content (and its reports) without banning the user
    - [x] ban the user: don't delete the user, give them permission level -1 banned. These guys must be kept in the DB so they can’t rejoin the app with their knights email, but we can delete their content.
         - [x] make user status -1
    - [x] Get all active reports: QueryCursor over reported content (sort by desc number of reports)
    - [x] maintain a moderation log in firebase:modHistory (employees give a reason for deleting the content / user)
    - [x] Get all modHistory entries: QueryCursor (sort by desc timestamp): Employees will be able to view a log of all previous moderation actions taken. This will be just one page, with a card of mod info per user where action has been taken.

Figma idea:
![image](https://user-images.githubusercontent.com/73561858/215092745-32789b2f-0b1e-43e1-8079-d5030692666b.png)

Clicking on a report: 
![image](https://user-images.githubusercontent.com/73561858/215094237-e9fd3ab8-0666-4d01-9e71-c865f1583b28.png)
