### ISSUE TITLE
Users can be promoted

### ISSUE THREAD

**Issue by JakeSteinebronn** [ucf-tower-app/xplat#88]
### Tasks for this requirement:
- [x] `approveOtherUser(auth, otherUser)`
- [x] `promoteOtherToEmployee(auth, otherUser)`
- [x] `makeOtherManager(auth, password, otherUser)`

There can only be 1 manager, and that manager permission can be passed from Manager to Employee.
Developer accounts can just be manually set in firebase :)
